# Temel image
FROM node:20

# Çalışma dizinini ayarla
WORKDIR /app

# package.json ve package-lock.json'u kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install

# Geriye kalan dosyaları kopyala
COPY . .

# Portu aç
EXPOSE 3000

# Uygulamayı başlat
CMD ["npm", "run","start"]
