version: "3.9"

services:
  nodeapp:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
